### ISSUE TITLE
Problem with "persistent" caching token

### ISSUE THREAD

**Issue by mkaczm01** [gregurco/GuzzleBundleOAuth2Plugin#19]
I encountered a problem with caching tokens. 

I change option in config like in documentation:
`persistent: true`

And the problem is:
> Cache item "oauth.token.api_sso" comes from a non tag-aware pool: you cannot tag it.

The temporary fix I made:
![image](https://user-images.githubusercontent.com/816162/51522761-6563a680-1e2a-11e9-9301-fc97c3323e8b.png)

I commented line 83 in file: **vendor/gregurco/guzzle-bundle-oauth2-plugin/src/Middleware/CachedOAuthMiddleware.php**

Also I observed that this error is trrigerred only when item is inserted to cache for the first time. When the item is in cache and I uncommented the line everything is working.

**Symfony:** 4.2.2
**GuzzleBundleOAuth2Plugin:** 1.0.7

**Comment by gregurco** [comment]
@Fragles hello! Sorry for delay. I checked this issue and I think we can totally remove tag. What do you think? Do you use tag functionality?

**Comment by mkaczm01** [comment]
As I read on Symfony blog here:
https://symfony.com/blog/new-in-symfony-3-2-tagged-cache

In this plugin there is no use of tag so it can be safely remove I think. 
I will test this solution for few days.

**Comment by gregurco** [comment]
@Fragles ok, please write here the result of test and if it's safe to be removed then I will do changes and new release.
Thanks!

**Comment by mkaczm01** [comment]
@gregurco I think it is safe to remove tag.

**Comment by gregurco** [comment]
@Fragles thank you for information. Created and merged PR #20.

**Comment by gregurco** [comment]
@Fragles released https://github.com/gregurco/GuzzleBundleOAuth2Plugin/releases/tag/v1.0.8
