### ISSUE TITLE
Guzzle 7

### ISSUE THREAD

**Issue by moux2003** [gregurco/GuzzleBundleOAuth2Plugin#27]
Hello,

I just wonder if there is a possibility to have guzzle 7 dependency (like in cache plugin) or if there is a reason not to ?

Thanks

**Comment by aless673** [comment]
@moux2003 no reason : https://github.com/aless673/GuzzleBundleOAuth2Plugin

**Comment by gregurco** [comment]
Released: https://github.com/gregurco/GuzzleBundleOAuth2Plugin/releases/tag/v2.2.0
