### ISSUE TITLE
Error when using with Symfony 4

### ISSUE THREAD

**Issue by rfsbsb** [gregurco/GuzzleBundleOAuth2Plugin#9]
When I try to use it with Symfony for I got the following error:

Unrecognized option "oauth2" under "eight_points_guzzle.clients.my_client.plugin"

**Comment by gregurco** [comment]
@rfsbsb yep, we know about the problem with SF4. The initializing of bundles was changed there and current plugin system is not compatible with it. We're trying to find solution. I will write here, when it's done.

**Comment by gregurco** [comment]
@rfsbsb https://github.com/8p/EightPointsGuzzleBundle/pull/183#issuecomment-376462603 - you can use it as temporary solution.

**Comment by BallisticPain** [comment]
Going to try the temporary solution... apparently I need to install using dev-master hehe so I don't get the wrong version of `symfony\config`.

**Comment by gregurco** [comment]
@BallisticPain it's already updated, but not released: https://github.com/gregurco/GuzzleBundleOAuth2Plugin/blob/master/composer.json#L26 . Could you install `dev-master` version or do you need release?

**Comment by BallisticPain** [comment]
@gregurco You're quick this morning! lol Thanks! `dev-master` is fine with me.

**Comment by gregurco** [comment]
@BallisticPain you are welcome :slightly_smiling_face: And just few minutes ago I released `v1.0.4`. You can use it.

**Comment by nurtext** [comment]
Hi @gregurco, what's the new way to implement the plugin into sf4?

**Comment by gregurco** [comment]
@nurtext please follow suggestion from this comment: https://github.com/8p/EightPointsGuzzleBundle/pull/183#issuecomment-376462603

**Comment by nurtext** [comment]
@gregurco Thanks, got it working 😉

**Comment by gregurco** [comment]
Added guide how to install in SF4 in PR #13
